name: Pull Request

on:
  push:
    branches:
      - main
  pull_request:
  workflow_call:

jobs:
  linting:
    name: Linting
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: Install dependencies
        run: python3 -m pip install tox
      - name: Run linters
        run: tox -vve lint
  unit-test:
    name: Unit tests
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: Install dependencies
        run: python -m pip install tox
      - name: Run tests
        run: tox -e unit
  integration:
    name: Integration tests (microk8s)
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Setup Kubernetes environment
        uses: balchua/microk8s-actions@v0.3.2
        with:
          channel: '1.30/stable'

      - name: Run integration tests
        run: tox -vve integration
